---
  version: '3.5'

  secrets:
    ssl_crt:
      file: ./config/certificates/wildcard-dev.crt
    ssl_key:
      file: ./config/certificates/wildcard-dev.key
      
  services:
    mlr-legacy-transformer-service:
      build: .
      image: mlr-legacy-transformer-service
      secrets:
        - source: ssl_crt
          target: /home/python/certificates/wildcard-ssl.crt
        - source: ssl_key
          target: /home/python/certificates/wildcard-ssl.key
      ports:
        - "7010:7010"
      env_file:
        - config.env
        - secrets.env
